version: 2
jobs:
  build:
    working_directory: /go/src/github.com/GoodCodingFriends/gpay
    docker:
      - image: ktr0731/circleci-gpay
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_HOST: "%"
          MYSQL_HOST: 127.0.0.1

    steps:
      - checkout

      - run:
          name: wait until waking up MySQL
          command: |
            for i in $(seq 60)
            do
              mysql -h 127.0.0.1 -u root -e 'show databases' || (sleep 1; false) && break
            done

      - run:
          name: migrate
          command: mysql -h 127.0.0.1 -u root < database/schema.sql

      - run:
          name: build
          command: make build

      - run:
          name: test
          command: make test
